<?xml version="1.0"?>
<package format="2">
  <name>mpc_controller</name>
  <version>0.0.0</version>
  <description>
    MPC node that consumes vehicle pose and a ZED depth occupancy grid and
    outputs control commands to MAVROS.
  </description>

  <maintainer email="kmk9595@gmail.com">rogx</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <!-- Python node -->
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>visualization_msgs</build_depend>
  <build_depend>mavros_msgs</build_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>mavros_msgs</exec_depend>
  <exec_depend>python3-scipy</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>mavros</exec_depend>

  <export>
  </export>
</package>
