#!/usr/bin/python
# -*- coding: utf-8 -*-
"""Controller-independent types for the fixed-altitude planar planner.

Nothing in this module imports ROS, mavros, PX4 or a simulator. That is the
point: the planner produces a reference described only by numpy arrays, and the
adapter that turns it into a PositionTarget (or a geometric-controller input,
or a behaviour-cloning training sample) lives outside.

    PlanarState              one planar state xi = [x y vx vy psi omega]
    PlanarReferenceSequence  the planar plan: p, v, a, psi, psi_dot over N+1 nodes
    FixedAltitudeReference   the same lifted to 3D at a constant z0
    ReferencePoint           one sample of either, for the 20 Hz publish loop
    MPPIResult               outcome of one solve, including which fallback ran

A future HPA (behaviour-cloned high-performance autonomy) is expected to emit a
PlanarReferenceSequence too, so that the switch between HAA and HPA is a swap of
the producer and nothing downstream changes.

STATE / INPUT LAYOUT
    xi = [x, y, vx, vy, psi, omega]        world-frame planar position and
                                           velocity, heading, heading rate
    nu = [ax, ay, alpha]                   world-frame planar acceleration and
                                           heading acceleration

Roll and pitch are deliberately absent. They are generated by the low-level
controller from the acceleration reference, and are not planning variables.
"""

import numpy as np

# ---------------------------------------------------------------- dimensions

NXI = 6                     # planar state dimension
NNU = 3                     # planar input dimension

# state indices
IX, IY, IVX, IVY, IPSI, IOM = range(NXI)
S_POS = slice(0, 2)
S_VEL = slice(2, 4)

# input indices
IAX, IAY, IAL = range(NNU)
U_ACC = slice(0, 2)


def wrap_angle(a):
    """Wrap to (-pi, pi]. Works on scalars and arrays."""
    return np.arctan2(np.sin(a), np.cos(a))


def angle_lerp(a0, a1, s):
    """Interpolate between two angles the short way round."""
    return wrap_angle(a0 + wrap_angle(a1 - a0) * s)


# --------------------------------------------------------------------- state

class PlanarState(object):
    """One planar state. Thin, but it keeps callers from indexing by number."""

    __slots__ = ("x", "y", "vx", "vy", "psi", "omega")

    def __init__(self, x=0.0, y=0.0, vx=0.0, vy=0.0, psi=0.0, omega=0.0):
        self.x = float(x)
        self.y = float(y)
        self.vx = float(vx)
        self.vy = float(vy)
        self.psi = float(wrap_angle(psi))
        self.omega = float(omega)

    @classmethod
    def from_array(cls, xi):
        xi = np.asarray(xi, dtype=np.float64).reshape(-1)
        if xi.size != NXI:
            raise ValueError("planar state must have %d elements, got %d"
                             % (NXI, xi.size))
        return cls(*xi)

    def to_array(self):
        return np.array([self.x, self.y, self.vx, self.vy, self.psi,
                         self.omega], dtype=np.float64)

    @property
    def position(self):
        return np.array([self.x, self.y])

    @property
    def velocity(self):
        return np.array([self.vx, self.vy])

    @property
    def speed(self):
        return float(np.hypot(self.vx, self.vy))

    def __repr__(self):
        return ("PlanarState(p=(%.3f, %.3f), v=(%.3f, %.3f), psi=%.3f, "
                "omega=%.3f)" % (self.x, self.y, self.vx, self.vy, self.psi,
                                 self.omega))


# ----------------------------------------------------------------- reference

class ReferencePoint(object):
    """A single reference sample handed to the low-level controller.

    p, v, a are length-2 (planar) or length-3 (lifted) arrays depending on
    which sequence produced it.
    """

    __slots__ = ("p", "v", "a", "psi", "psi_dot")

    def __init__(self, p, v, a, psi, psi_dot):
        self.p = np.asarray(p, dtype=np.float64)
        self.v = np.asarray(v, dtype=np.float64)
        self.a = np.asarray(a, dtype=np.float64)
        self.psi = float(psi)
        self.psi_dot = float(psi_dot)

    def __repr__(self):
        return ("ReferencePoint(p=%s, v=%s, a=%s, psi=%.3f, psi_dot=%.3f)"
                % (np.round(self.p, 3).tolist(), np.round(self.v, 3).tolist(),
                   np.round(self.a, 3).tolist(), self.psi, self.psi_dot))


class _SequenceBase(object):
    """Shared sampling logic for the planar and lifted reference sequences."""

    __slots__ = ("p", "v", "a", "psi", "psi_dot", "dt")

    def __len__(self):
        return int(self.p.shape[0])

    @property
    def n_nodes(self):
        return int(self.p.shape[0])

    @property
    def horizon(self):
        """Number of control intervals, i.e. n_nodes - 1."""
        return int(self.p.shape[0]) - 1

    @property
    def duration(self):
        return self.horizon * self.dt

    def sample(self, t):
        """Reference at time t seconds after the plan start, clamped to the ends.

        Linear in p/v/a, short-way-round in psi. Clamping rather than
        extrapolating matters: a stale plan then degrades to "hold the last
        node", not "keep accelerating off the end of the horizon".
        """
        n = self.n_nodes
        s = float(t) / self.dt
        s = min(max(s, 0.0), float(n - 1))
        i = int(np.floor(s))
        if i >= n - 1:
            i = n - 2 if n >= 2 else 0
        f = s - i
        j = min(i + 1, n - 1)
        return ReferencePoint(
            self.p[i] + (self.p[j] - self.p[i]) * f,
            self.v[i] + (self.v[j] - self.v[i]) * f,
            self.a[i] + (self.a[j] - self.a[i]) * f,
            angle_lerp(self.psi[i], self.psi[j], f),
            self.psi_dot[i] + (self.psi_dot[j] - self.psi_dot[i]) * f)

    def node(self, k):
        return ReferencePoint(self.p[k], self.v[k], self.a[k],
                              self.psi[k], self.psi_dot[k])


class PlanarReferenceSequence(_SequenceBase):
    """The planner's native output: N+1 nodes of planar reference.

    p       (N+1, 2)  world xy position
    v       (N+1, 2)  world xy velocity
    a       (N+1, 2)  world xy acceleration. The input sequence only has N
                      entries, so a[N] repeats a[N-1] -- a zero-order hold past
                      the horizon end, which is what the controller would see
                      anyway if the plan went stale there.
    psi     (N+1,)    heading
    psi_dot (N+1,)    heading rate
    """

    __slots__ = ()

    def __init__(self, p, v, a, psi, psi_dot, dt):
        self.p = np.asarray(p, dtype=np.float64).reshape(-1, 2)
        self.v = np.asarray(v, dtype=np.float64).reshape(-1, 2)
        self.a = np.asarray(a, dtype=np.float64).reshape(-1, 2)
        self.psi = np.asarray(psi, dtype=np.float64).reshape(-1)
        self.psi_dot = np.asarray(psi_dot, dtype=np.float64).reshape(-1)
        self.dt = float(dt)
        n = self.p.shape[0]
        for name, arr in (("v", self.v), ("a", self.a),
                          ("psi", self.psi), ("psi_dot", self.psi_dot)):
            if arr.shape[0] != n:
                raise ValueError("reference field %r has %d nodes, p has %d"
                                 % (name, arr.shape[0], n))

    @classmethod
    def from_rollout(cls, X, U, dt):
        """Build from a rolled-out state trajectory and its input sequence.

        X (N+1, 6), U (N, 3).
        """
        X = np.asarray(X, dtype=np.float64)
        U = np.asarray(U, dtype=np.float64)
        a = np.concatenate([U[:, U_ACC], U[-1:, U_ACC]], axis=0)
        return cls(X[:, S_POS], X[:, S_VEL], a, X[:, IPSI], X[:, IOM], dt)

    def lift(self, z0):
        """Lift to a fixed-altitude 3D reference.

        z is constant, so vz = az = 0 by construction. Holding altitude against
        gravity is the low-level controller's job, not the planner's -- the
        planner never had z as a state, so it must not pretend to command a
        vertical acceleration.
        """
        n = self.n_nodes
        zeros = np.zeros((n, 1))
        p3 = np.concatenate([self.p, np.full((n, 1), float(z0))], axis=1)
        v3 = np.concatenate([self.v, zeros], axis=1)
        a3 = np.concatenate([self.a, zeros], axis=1)
        return FixedAltitudeReference(p3, v3, a3, self.psi, self.psi_dot,
                                      self.dt, z0)

    def shifted(self, k=1):
        """Drop the first k nodes and hold the last one, for plan continuation.

        The tail is padded by repeating the final node with its velocity and
        acceleration zeroed, so continuing a stale plan past its end coasts to a
        stop at the last committed position instead of running off the horizon.
        """
        k = int(k)
        if k <= 0:
            return self
        n = self.n_nodes
        if k >= n - 1:
            k = n - 2 if n >= 2 else 0
        p = self.p[k:]
        v = self.v[k:]
        a = self.a[k:]
        psi = self.psi[k:]
        pd = self.psi_dot[k:]
        pad = k
        if pad > 0:
            p = np.concatenate([p, np.repeat(p[-1:], pad, axis=0)], axis=0)
            v = np.concatenate([v, np.zeros((pad, 2))], axis=0)
            a = np.concatenate([a, np.zeros((pad, 2))], axis=0)
            psi = np.concatenate([psi, np.repeat(psi[-1:], pad)], axis=0)
            pd = np.concatenate([pd, np.zeros(pad)], axis=0)
        return PlanarReferenceSequence(p, v, a, psi, pd, self.dt)


class FixedAltitudeReference(_SequenceBase):
    """PlanarReferenceSequence lifted to 3D at a constant altitude z0.

    This is what the existing PX4 / geometric controller consumes:
        p_d = [x, y, z0], v_d = [vx, vy, 0], a_d = [ax, ay, 0], psi_d, psi_dot_d
    """

    __slots__ = ("z0",)

    def __init__(self, p, v, a, psi, psi_dot, dt, z0):
        self.p = np.asarray(p, dtype=np.float64).reshape(-1, 3)
        self.v = np.asarray(v, dtype=np.float64).reshape(-1, 3)
        self.a = np.asarray(a, dtype=np.float64).reshape(-1, 3)
        self.psi = np.asarray(psi, dtype=np.float64).reshape(-1)
        self.psi_dot = np.asarray(psi_dot, dtype=np.float64).reshape(-1)
        self.dt = float(dt)
        self.z0 = float(z0)


# -------------------------------------------------------------------- result

class PlannerStatus(object):
    """Which branch of the safety chain produced the returned trajectory.

    Ordered from best to worst. Anything other than FAILED carries a validated
    trajectory; the status says how much of the MPPI update survived, which is
    the signal a supervisor should watch -- a run that spends its time in
    BEST_SAMPLE or PREVIOUS is one replan away from BRAKING.
    """

    WEIGHTED = "WEIGHTED"          # full MPPI update accepted (beta = 1)
    DAMPED = "DAMPED"              # damped update accepted (beta < 1)
    BEST_SAMPLE = "BEST_SAMPLE"    # weighted update unsafe, used lowest-cost sample
    PREVIOUS = "PREVIOUS"          # no valid sample, continued the last plan
    BRAKING = "BRAKING"            # no previous plan, braking to hover
    FAILED = "FAILED"              # nothing valid exists

    OK = (WEIGHTED, DAMPED, BEST_SAMPLE, PREVIOUS, BRAKING)
    DEGRADED = (BEST_SAMPLE, PREVIOUS, BRAKING)


class MPPIResult(object):
    """Outcome of one solve."""

    __slots__ = ("status", "reference", "U", "X", "cost", "n_valid",
                 "n_samples", "beta", "reason", "X_viz", "solve_time")

    def __init__(self, status, reference=None, U=None, X=None,
                 cost=float("inf"), n_valid=0, n_samples=0, beta=0.0,
                 reason="", X_viz=None, solve_time=0.0):
        self.status = status
        self.reference = reference      # PlanarReferenceSequence or None
        self.U = U                      # (N, 3) accepted input sequence
        self.X = X                      # (N+1, 6) accepted state trajectory
        self.cost = cost
        self.n_valid = n_valid
        self.n_samples = n_samples
        self.beta = beta
        self.reason = reason
        self.X_viz = X_viz              # (n, N+1, 6) surviving samples, for rviz
        self.solve_time = solve_time

    @property
    def ok(self):
        """True when a validated trajectory is available."""
        return self.status in PlannerStatus.OK

    @property
    def degraded(self):
        """True when the MPPI update itself was rejected."""
        return self.status in PlannerStatus.DEGRADED

    def __repr__(self):
        return ("MPPIResult(%s, valid=%d/%d, beta=%.3g, cost=%.3f, %r)"
                % (self.status, self.n_valid, self.n_samples, self.beta,
                   self.cost, self.reason))
